I'm sorry, but an uncaught exception occurred.

While running game code:
  File "renpy/common/00start.rpy", line 195, in script
    python:
  File "renpy/common/00start.rpy", line 196, in <module>
    renpy.execute_default_statement(True)
  File "game/script.rpy", line 20, in execute_default
    default vitals = False
Exception: store.vitals is being given a default a second time.

-- Full Traceback ------------------------------------------------------------

Full traceback:
  File "renpy/common/00start.rpy", line 195, in script
    python:
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\ast.py", line 834, in execute
    renpy.python.py_exec_bytecode(self.code.bytecode, self.hide, store=self.store)
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\python.py", line 1187, in py_exec_bytecode
    exec(bytecode, globals, locals)
  File "renpy/common/00start.rpy", line 196, in <module>
    renpy.execute_default_statement(True)
  File "D:\Ren'Py\renpy-8.3.7-sdk\renpy\exports\statementexports.py", line 372, in execute_default_statement
    i.execute_default(start)
  File "game/script.rpy", line 20, in execute_default
    default vitals = False
Exception: store.vitals is being given a default a second time.

Windows-10-10.0.19045 AMD64
Ren'Py 8.3.7.25031702
Bug Wife Turbo Space Hell 0.2
Sun Jul  6 00:02:39 2025
